### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Shinichi-Sonoda** [Shinichi-Sonoda/furima-37901#22]
URL: https://furima-37901.herokuapp.com/

Basic認証
ID:  admin
PW: 2222

出品者用アカウント
Email: test@test
PW: test111

購入者用アカウント
Email: sample@sample
PW: sample111

**Comment by snkw-works** [comment]
@Shinichi-Sonoda さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されるよう修正しましょう**
「新品・未使用」「未使用に近い」が一項目として表示されています。
<img width="375" alt="スクリーンショット_2022-05-10_16_41_35" src="https://user-images.githubusercontent.com/54050089/167578253-c2365ea3-44e8-44ad-962a-6870a0d9a3a4.png">

- [x] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができるよう修正しましょう**
現状、正しい情報を入力して購入ボタンをクリックするとエラー画面に遷移してしまい、購入が完了できない状態です。
<img width="725" alt="スクリーンショット 2022-05-10 16 50 57" src="https://user-images.githubusercontent.com/54050089/167577505-44143105-db64-47ae-99b7-607b88d8e815.png">

※購入機能と購入後に関する項目に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

[補足]
商品詳細ページにてヘッダーが表示されていない状態です。必須要件とはなっておりませんが、可能であれば見本アプリと同様に、詳細ページにもヘッダーが表示されるよう修正しましょう。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Shinichi-Sonoda** [comment]
# what
挙動確認

# why
よろしくお願い致します。

**Comment by snkw-works** [comment]
@Shinichi-Sonoda さん、フリマアプリ達成要件分の開発お疲れ様でした！
修正が確認でき、正常に動作することが確認できました！ **LGTM** です！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

#### ＜今後の学習例＞
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。

また、以下提出物に関するリマインドです。

#### ＜提出物＞
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

#### ＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/7105

今後の流れに関して、もしご不明点がございましたら、担当ライフコーチまでお気兼ねなくお申し付けくださいませ。

![lgtm_01](https://user-images.githubusercontent.com/54050089/164166779-9eca4a1e-955a-4d55-bfa3-c0ff25e73e87.png)
